# Generated by Django 5.0.7 on 2024-07-29 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_user_isverified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='isVerified',
            new_name='is_verified',
        ),
    ]
