# Generated by Django 5.0.7 on 2024-07-29 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_rename_isverified_user_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verification_code',
            field=models.IntegerField(default=333333),
            preserve_default=False,
        ),
    ]
